/* constant string data definitions*/

defines(void)
{

struct room
{
        char *contents;
        char *id;
};


extern struct room dungeon[34];
extern char *cause[8], *effect[8], *species[4], *bad_response, *gold[14], *treasure[16];
extern char *frog[42], *hint[16], *royal[6], *curse[6], *sss[10], *monster[7], *noise[7];
extern char *command[52], *pad, *qpad, *dots;
extern char *strength, *intelligence, *dexterity;

strength = "STRENGTH";
intelligence = "INTELLIGENCE";
dexterity = "DEXTERITY";
pad = "     ";
qpad = "          ";
dots = ".....";

dungeon[0].contents = "AN EMPTY ROOM";
dungeon[0].id = ".";
dungeon[1].contents = "THE ENTRANCE";
dungeon[1].id = "E";
dungeon[2].contents = "STAIRS GOING UP";
dungeon[2].id = "U";
dungeon[3].contents = "STAIRS GOING DOWN";
dungeon[3].id = "D";
dungeon[4].contents = "A POOL";
dungeon[4].id = "P";
dungeon[5].contents = "A CHEST";
dungeon[5].id = "C";
dungeon[6].contents = "GOLD PIECES";
dungeon[6].id = "G";
dungeon[7].contents = "FLARES";
dungeon[7].id = "F";
dungeon[8].contents = "A WARP";
dungeon[8].id = "W";
dungeon[9].contents = "A SINKHOLE";
dungeon[9].id = "S";
dungeon[10].contents = "A CRYSTAL ORB";
dungeon[10].id = "O";
dungeon[11].contents = "A BOOK";
dungeon[11].id = "B";
dungeon[12].contents = "A KOBOLD";
dungeon[12].id = "M";
dungeon[13].contents = "AN ORC";
dungeon[13].id = "M";
dungeon[14].contents = "A GOBLIN";
dungeon[14].id = "M";
dungeon[15].contents = "AN OGRE";
dungeon[15].id = "M";
dungeon[16].contents = "A TROLL";
dungeon[16].id = "M";
dungeon[17].contents = "A HARPY";
dungeon[17].id = "M";
dungeon[18].contents = "A CYCLOPS";
dungeon[18].id = "M";
dungeon[19].contents = "A MINOTAUR";
dungeon[19].id = "M";
dungeon[20].contents = "A GARGOYLE";
dungeon[20].id = "M";
dungeon[21].contents = "A CHIMERA";
dungeon[21].id = "M";
dungeon[22].contents = "A BALROG";
dungeon[22].id = "M";
dungeon[23].contents = "A DRAGON";
dungeon[23].id = "M";
dungeon[24].contents = "A VENDOR";
dungeon[24].id = "V";
dungeon[25].contents = "THE RED RUBY";
dungeon[25].id = "T";
dungeon[26].contents = "THE NORN STONE";
dungeon[26].id = "T";
dungeon[27].contents = "THE PALE PEARL";
dungeon[27].id = "T";
dungeon[28].contents = "THE OPAL EYE";
dungeon[28].id = "T";
dungeon[29].contents = "THE GREEN GEM";
dungeon[29].id = "T";
dungeon[30].contents = "THE BLUE FLAME";
dungeon[30].id = "T";
dungeon[31].contents = "THE PALANTIR";
dungeon[31].id = "T";
dungeon[32].contents = "THE SILMARIL";
dungeon[32].id = "T";
dungeon[33].contents = "\0";
dungeon[33].id = "?";

cause[0] = "NO WEAPON";
effect[0] = " SANDWICH";
cause[1] = "DAGGER";
effect[1] = " STEW";
cause[2] = "MACE";
effect[2]  = " SOUP";
cause[3]  = "SWORD";
effect[3]  = " BURGER";
cause[4]  = "NO ARMOR";
effect[4]  = " ROAST";
cause[5]  = "LEATHER";
effect[5]  = " FILET";
cause[6]  = "CHAINMAIL";
effect[6]  = " TACO";
cause[7]  = "PLATE";
effect[7]  = " PIE";

species[0] = "HOBBIT";
species[1] = "ELF";
species[2] = "HUMAN";
species[3] = "DWARF";

bad_response = "     ** PLEASE!!!  CHOOSE A REASONABLE RESPONSE.";

gold[0] = "ENGLISH SOVEREIGNS";
gold[1] = "ARGENTINE PESOS";
gold[2] = "SWISS DUCATS";
gold[3] = "MEXICAN ESCUDOS";
gold[4] = "PERUVIAN SOLES";
gold[5] = "AMERICAN EAGLES";
gold[6] = "SPANISH DOUBLOONS";
gold[7] = "FRENCH FRANCS";
gold[8] = "GERMAN DUCATS";
gold[9] = "TURKISH PIASTRES";
gold[10] = "INDIAN MOHURS";
gold[11] = "AUSTRIAN KRONES";
gold[12] = "RUSSIAN ROUBLES";
gold[13] = "POLISH ZLOTYCHS";

treasure[0] = "Red Ruby";
treasure[1] = "Norn Stone";
treasure[2] = "Pale Pearl";
treasure[3] = "Opal Eye";
treasure[4] = "Green Gem";
treasure[5] = "Blue Flame";
treasure[6] = "Palantir";
treasure[7] = "Silmaril";
treasure[8] = "RED RUBY";
treasure[9] = "NORN STONE";
treasure[10] = "PALE PEARL";
treasure[11] = "OPAL EYE";
treasure[12] = "GREEN GEM";
treasure[13] = "BLUE FLAME";
treasure[14] = "PALANTIR";
treasure[15] = "SILMARIL";

frog[0] = " CRICKET";
frog[1] = " STRIPED CHORUS";
frog[2] = " SPRING PEEPER";
frog[3] = " COMMON TREE";
frog[4] = " GOPHER";
frog[5] = " BULL";
frog[6] = " PICKEREL";
frog[7] = " LEOPARD";
frog[8] = " WOOD";
frog[9] = " NARROW-MOUTHED";
frog[10] = " PLAINS";
frog[11] = " GREEN";
frog[12] = " CANYON";
frog[13] = "n AMERICAN";
frog[14] = " GARDEN";
frog[15] = " COMMON MUSK";
frog[16] = " YELLOW MUD";
frog[17] = "n ALLIGATOR SNAPPING";
frog[18] = " COMMON SNAPPING";
frog[19] = " MAP";
frog[20] = " CAROLINA BOX";
frog[21] = "n ORNATE BOX";
frog[22] = " FALSE MAP";
frog[23] = " WESTERN PAINTED";
frog[24] = "n ELEGANT SLIDER";
frog[25] = "n EARLESS";
frog[26] = " COLLARED";
frog[27] = " ROUGH-SCALED";
frog[28] = " TEXAS HORNED";
frog[29] = " SHORT-HORNED";
frog[30] = " BROWN";
frog[31] = " COAL";
frog[32] = " FIVE-LINED";
frog[33] = " SONORAN";
frog[34] = " PRAIRIE";
frog[35] = "FROG";
frog[36] = "FROG";
frog[37] = "TOAD";
frog[38] = "TURTLE";
frog[39] = "TURTLE";
frog[40] = "LIZARD";
frog[41] = "SKINK";

hint[0] = "Physical attacks rarely kill Gargoyles";
hint[1] = "Lizards and Skinks have gold for you";
hint[2] = "It's dangerous to keep too much gold";
hint[3] = "Go chase someone who can give you a race";
hint[4] = "Many thanks to Joseph Power & Verne Walrafen";
hint[5] = "Dragons are magical creatures";
hint[6] = "Report any problems to Ms. Bird";
hint[7] = "Leslie Bird (nightflyte@gmail.com)";
hint[8] = "Gems are much nicer than gold";
hint[9] = "Copy this PUBLIC DOMAIN game for your friends";
hint[10] = "Only the quick afoot survive";
hint[11] = "Do I look like a FROG?  Put me down";
hint[12] = "You might have to kiss a lot of frogs";
hint[13] = "Watch out for WITCHES...wicked and good";
hint[14] = "There are three royal siblings";
hint[15] = "Knowledge of ZOT's small gift proves WIN";

royal[0] = "UGLY";
royal[1] = "5 YEAR OLD";
royal[2] = "HANDSOME";
royal[3] = "PLAIN";
royal[4] = "OLD MAID";
royal[5] = "BEAUTIFUL";

curse[0] = "LETHARGY.";
curse[1] = "THE LEECH.";
curse[2] = "FORGETFULNESS.";
curse[3] = "lethargy.";
curse[4] = "the leech.";
curse[5] = "forgetfulness.";

sss[0] = "\0";
sss[1] = "SS";
sss[2] = "FEMALE ";
sss[3] = "MALE ";
sss[4] = "NORTH";
sss[5] = "SOUTH";
sss[6] = "EAST";
sss[7] = "WEST";
sss[8] = "GOOD";
sss[9] = "EVIL";

monster[0] = "Harpy";
monster[1] = "Gargoyle";
monster[2] = "Dragon";
monster[3] = "Frog";
monster[4] = "Toad";
monster[5] = "Lizard";
monster[6] = "Skink";

noise[0] = "a scream";
noise[1] = "footsteps";
noise[2] = "a CRAZY programmer";
noise[3] = "frogs croaking";
noise[4] = "faint rustling noises";
noise[5] = "see a BAT fly by";
noise[6] = "find a VERY dead frog";

command[0] = "*NO";
command[1] = "YYES";
command[2] = "*YES";
command[3] = "NNO";
command[4] = "*ELF";
command[5] = "DDWARF";
command[6] = "MHUMAN";
command[7] = "HHOBBIT";
command[8] = "*LEATHER";
command[9] = "CCHAINMAIL";
command[10] = "PPLATE";
command[11] = "*SWORD";
command[12] = "NNONE";
command[13] = "DDAGGER";
command[14] = "MMACE";
command[15] = "******";
command[16] = "NNORTH";
command[17] = "EEAST";
command[18] = "SSOUTH";
command[19] = "WWEST";
command[20] = "LLOOK";
command[21] = "UUP";
command[22] = "DDOWN";
command[23] = "MMAP";
command[24] = "HHELP";
command[25] = "FFLARE";
command[26] = "CCATCH";
command[27] = "KKISS";
command[28] = "IDRINK";
command[29] = "RRELEASE";
command[30] = "OOPEN";
command[31] = "GGAZE";
command[32] = "TTELEPORT";
command[33] = "ZZOT";
command[34] = "QQUIT";
command[35] = "/";
command[36] = "*IGNORE";
command[37] = "TTRADE";
command[38] = "AATTACK";
command[39] = "******";
command[40] = "AATTACK";
command[41] = "BBRIBE";
command[42] = "CCAST";
command[43] = "RRETREAT";
command[44] = "DDEATH";
command[45] = "FFIREBALL";
command[46] = "WWEBB";
command[47] = "******";
command[48] = "MMALE";
command[49] = "FFEMALE";
command[50] = "*NEW";
command[51] = "OOLD";

return 0;
}
